// File automatically generated by swift-bridge.
#include <stdint.h>
typedef struct Expression Expression;
void __swift_bridge__$Expression$_free(void* self);

void* __swift_bridge__$Vec_Expression$new(void);
void __swift_bridge__$Vec_Expression$drop(void* vec_ptr);
void __swift_bridge__$Vec_Expression$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_Expression$pop(void* vec_ptr);
void* __swift_bridge__$Vec_Expression$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_Expression$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_Expression$len(void* vec_ptr);
void* __swift_bridge__$Vec_Expression$as_ptr(void* vec_ptr);

struct __private__ResultPtrAndPtr __swift_bridge__$parse_text(struct RustStr input);
struct __private__ResultPtrAndPtr __swift_bridge__$parse_latex_ffi(struct RustStr input);
void* __swift_bridge__$expression_to_string(void* expr);
void* __swift_bridge__$expression_to_latex(void* expr);
void* __swift_bridge__$expression_find_variables(void* expr);
void* __swift_bridge__$expression_find_functions(void* expr);
void* __swift_bridge__$expression_find_constants(void* expr);
uintptr_t __swift_bridge__$expression_depth(void* expr);
uintptr_t __swift_bridge__$expression_node_count(void* expr);
struct __private__ResultPtrAndPtr __swift_bridge__$expression_to_json(void* expr);
struct __private__ResultPtrAndPtr __swift_bridge__$expression_to_json_pretty(void* expr);


